Repository atlp-rwanda/commanders-medica-backoffice, pull requests merged in 2024-07, with the labels that each got.

#4 Feature: dashboard login and signup functionality
  app/auth/actions.ts
  app/auth/layout.tsx
  app/auth/login/page.tsx
  app/auth/signup/page.tsx
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components/guest/navbar.tsx
  public/android-chrome-96x96.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
Labels: feature

#6 Feature: Implement the admin dashboard UI
  app/dashboard/page.tsx
  app/globals.css
  assets/icons/accordion.svg
  assets/icons/calendar.svg
  assets/icons/cough.svg
  assets/icons/downward.svg
  assets/icons/fever.svg
  assets/icons/heartburn.svg
  assets/icons/home.svg
  assets/icons/logout.svg
  assets/icons/menu.svg
  assets/icons/messages.svg
  assets/icons/notification.svg
  assets/icons/notify.svg
  assets/icons/reports.svg
  assets/icons/search.svg
  assets/icons/settings.svg
  assets/icons/threedots.svg
  assets/icons/upward.svg
  assets/images/article.png
  assets/images/doctor.png
  components/MainSection.tsx
  components/listItem.tsx
  components/navbar.tsx
  components/styles.css
  components/topbar.tsx
  next.config.mjs
  package-lock.json
  package.json
  utils/supabase/getUser.ts
Labels: feature, need review

#10 Feature: landing page design
  app/globals.css
  app/page.tsx
  components/guest/landing/findDoctor.tsx
  components/guest/landing/footer.tsx
  components/guest/landing/hero.tsx
  components/guest/landing/memberResults.tsx
  components/guest/landing/providedServices.tsx
  components/guest/landing/teamMembers.tsx
  components/guest/landing/testimonials.tsx
  components/guest/navbar.tsx
  public/images/doctors/doctor-1.png
  public/images/doctors/doctor-2.png
  public/images/doctors/doctor-3.png
  public/images/doctors/doctor-4.png
  public/images/doctors/doctor-5.png
  public/images/doctors/doctor-6.png
  public/images/operation.png
  public/images/services/bones.png
  public/images/services/cardiology.png
  public/images/services/dental.png
  public/images/services/diagnosis.png
  public/images/services/eye.png
  public/images/services/surgery.png
  public/images/team/andy-smith.png
  public/images/team/john-carter.png
  public/images/team/lilly-woods.png
  public/images/team/matt-cannon.png
  public/images/team/patrick-meyer.png
  public/images/team/sophie-moore.png
  public/images/testimonials/andy-smith.png
  public/images/testimonials/john-carter.png
  public/images/testimonials/sophie-moore.png
Labels: feature

#7 Feature: Implement the UI for the Messages and Messaging functionaly
  app/globals.css
  app/messages/page.tsx
  assets/icons/appareil.svg
  assets/icons/bluetick.svg
  assets/icons/camera.svg
  assets/icons/emoji.svg
  assets/icons/link.svg
  assets/icons/menublue.svg
  assets/icons/phone.svg
  assets/icons/play.svg
  assets/icons/record.svg
  assets/icons/send.svg
  assets/icons/stop.svg
  assets/icons/tick.svg
  assets/images/leg1.png
  assets/images/legs.png
  components/messages/audioRecorder.tsx
  components/messages/listMessages.tsx
  components/messages/messagesSection.tsx
  components/messages/sendMessage.tsx
  components/navbar.tsx
  package-lock.json
  package.json
  utils/supabase/getUser.ts
Labels: feature

#17 Chore: add linter and trigger on dev branch
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
Labels: chore

#15 Feature: Profile settings
  .env
  app/auth/actions.ts
  app/auth/login/page.tsx
  app/auth/newpassword/page.tsx
  app/auth/reset/page.tsx
  app/auth/signup/page.tsx
  app/auth/verify/page.tsx
  app/profile/page.tsx
  assets/images/profil.png
  components/navbar.tsx
  components/profile/inputFields.tsx
  components/profile/reviews.tsx
  components/profile/topElements.tsx
  components/profileSettings.tsx
  package-lock.json
Labels: feature, need review

#16 Feature: appointments dashboard
  .env
  .github/workflows/lint.yml
  .gitignore
  app/auth/actions.ts
  app/auth/newpassword/page.tsx
  app/auth/reset/page.tsx
  app/auth/verify/page.tsx
  app/dashboard/appointments/page.tsx
  app/dashboard/layout.tsx
  app/dashboard/messages/page.tsx
  app/dashboard/page.tsx
  app/dashboard/profile/page.tsx
  app/globals.css
  app/messages/page.tsx
  app/profile/page.tsx
  assets/spinner.png
  components/Loading.tsx
  components/MainSection.tsx
  components/dashboard/appointments/appointmentRequests.tsx
  components/dashboard/appointments/cancelledAppointments.tsx
  components/dashboard/appointments/upcomingAppointments.tsx
  components/listItem.tsx
  components/messages/audioRecorder.tsx
  components/messages/listMessages.tsx
  components/messages/messagesSection.tsx
  components/messages/sendMessage.tsx
  components/navbar.tsx
  components/profile/inputFields.tsx
  components/profile/reviews.tsx
  components/profile/topElements.tsx
  components/profileSettings.tsx
  components/topbar.tsx
  package-lock.json
  package.json
  tailwind.config.ts
  utils/supabase/middleware.ts
Labels: feature

#19 Feature: add appointment date filters
  .eslintrc.json
  Dockerfile
  app/dashboard/appointments/page.tsx
  components/MainSection.tsx
  components/dashboard/appointments/appointmentRequests.tsx
  components/dashboard/appointments/cancelledAppointments.tsx
  components/dashboard/appointments/helpers.ts
  components/dashboard/appointments/upcomingAppointments.tsx
  components/navbar.tsx
Labels: feature

#20 Feature: Doctors messaging first
  .github/workflows/deploy.yml
  app/dashboard/messages/page.tsx
  components/dashboard/appointments/upcomingAppointments.tsx
  components/messages/messagesSection.tsx
  utils/supabase/getUser.ts
Labels: feature, need review
